### ISSUE TITLE
B?Ut where is the code?

### ISSUE THREAD

**Issue by HunterEl** [acedrow/RPGTablePlayer#1]
I am an avid rpg player and need great table music written in a fantastic language. plz help. lol thnx

**Comment by acedrow** [comment]
Stalking my repos?

**Comment by acedrow** [comment]
It's gonna be in Alice, that's the only language I know after 3 years in
Beloit college csci.

**Comment by HunterEl** [comment]
Look I just want a fun and friendly experience on my favorite code hub. Please don't bully me and tell me how I can get my dank rpg music

**Comment by HunterEl** [comment]
thnk u
